### ISSUE TITLE
TypeError: str expected, not NoneType

### ISSUE THREAD

**Issue by rahulbakshee** [bwanglzu/Automatic-Question-Generation#25]
HI, i am trying to run like below:
$pwd
/c/Users/username/Automatic-Question-Generation/aqg

$ python app.py -f obama_short.txt 
 but i am getting following exception:

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\username/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\username/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\username/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
Traceback (most recent call last):
  File "app.py", line 72, in <module>
    print(pipeline(args.input))
  File "app.py", line 42, in pipeline
    gs = GapSelection()
  File "C:\Users\username\Automatic-Question-Generation\aqg\utils\gap_selection.py", line 16, in __init__
    'STANFORD_JARS')
  File "C:\Users\username\Continuum\anaconda3\lib\os.py", line 674, in __setitem__
    value = self.encodevalue(value)
  File "C:\Users\username\Continuum\anaconda3\lib\os.py", line 728, in check_str
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType

@bwanglzu  Can you please help me with that

**Comment by rahulbakshee** [comment]
I corrected the PATHs set and this error was gone

**Comment by bwanglzu** [comment]
@rahulbakshee good to know :)
