### ISSUE TITLE
Hi, thank you for providing this open source. Do you have a report or a paper on this algorithm?

### ISSUE THREAD

**Issue by caozhen-alex** [bwanglzu/Automatic-Question-Generation#28]
Hi, thank you for providing this open source. Do you have a report or a paper on this algorithm?

**Comment by bwanglzu** [comment]
hi @caozhen-alex , if my memory is correct, the idea comes from a combination of two papers, one is: Mind the Gap: Learning to Choose Gaps for Question Generation, another one was from a Microsoft research paper, but I forgot the name since the small project was done years before.
