### ISSUE TITLE
How do you create environment variables?

### ISSUE THREAD

**Issue by NSAryan12** [bwanglzu/Automatic-Question-Generation#29]
Hello @bwanglzu ,
would you please walk me through how to create "create environment variable file with: touch .env for configuration (in project root)."

I am really stuck, I have no clue.

Thanks
Aryan

**Comment by bwanglzu** [comment]
hi @NSAryan12 no worries, touch is a linux/osx command means create, you can create a file named `.env`, and add your configuration by editing the `.env`.

**Comment by NSAryan12** [comment]
@bwanglzu  so I basically make a touch .env file put all the code in it and add it
inside the Automatic-Question-Generation folder?

**Comment by NSAryan12** [comment]
thanks
